### ISSUE TITLE
What do I set the hostname as?

### ISSUE THREAD

**Issue by ghost** [nawar/kodi-cli#18]
I'm running kodi off my Raspberry pi and it's local IP is 192.168.0.15, so I set it as such, but this doesn't work.

**Comment by nawar** [comment]
There are instructions on using `.kodirc` within your home directory. Did you check that out? 

https://github.com/nawar/kodi-cli/blob/c7b7deda3fabf17e9e53c89eae5b672f068dc440/kodi-cli#L290-L296

**Comment by ghost** [comment]
Ohh, I got to move it to my home directory, I thought I just left it in the git directory
