### ISSUE TITLE
Add to Queue Option?

### ISSUE THREAD

**Issue by gotbletu** [nawar/kodi-cli#2]
could u add a queue option to add multiple youtube videos without stopping the current playing one.

something like
kodi-cli -q "https://www.youtube.com/watch?11111111"
kodi-cli -q "https://www.youtube.com/watch?2222222"
kodi-cli -q "https://www.youtube.com/watch?3333333"

**Comment by nawar** [comment]
Good suggestion. I'll find the time to add it.

**Comment by nawar** [comment]
Done. Please download the latest code. One note though, you'll need to add the first video with `-y` then add subsequent videos with `-q` while the first video is playing.
I had to do this as Kodi's queue wasn't clearing itself after it finishes playing the videos.

**Comment by gotbletu** [comment]
Thank you sir, it works good =)
