### ISSUE TITLE
I was able to add volume control - are you interested in updating the script?

### ISSUE THREAD

**Issue by elpraga** [nawar/kodi-cli#3]
Thank you for a great script!

It helped me so much! 

I did some searching and I was able to add volume control to your script, and it works like a charm mapped on a key press in fluxbox.

Would you be interested in adding it to your script?

**Comment by nawar** [comment]
Yes Please! Thanks!

**Comment by elpraga** [comment]
OK!
I tried to to it via pull-request, but it is the very first I did, so I hope I did it correctly..

**Comment by nawar** [comment]
Done!
