### ISSUE TITLE
Would you know how to add an option to play next track (video) from the playlist? 

### ISSUE THREAD

**Issue by elpraga** [nawar/kodi-cli#5]
It could be a nice feature, and I did try reading about it, but I did not managed to get it working.
I did all the changes as I did when adding the volume control, and I used the following function:

```
function play_next {
 # Get Active players first
  output=`xbmc_req '{"jsonrpc": "2.0", "method": "Player.GetActivePlayers", "id": 99}' true`
  player_id=`echo $output | parse_json "playerid"` 
  echo "Skipping to next item in playlist in the player with ID => $player_id"
  xbmc_req '{"jsonrpc": "2.0", "method": "Player.GoNext", "params": { "playerid": '$player_id' }, "id": 1}' 
}
```

When I extracted and exectured the command on a command line, and I got "Method not found" error. The syntax should have been ok, because Player.Stop worked fine from command line.

Have you got any idea why it did not work?

**Comment by nawar** [comment]
I haven't touched the script for sometime :) 
You can enable the -x option at the top which will show you what's the value of each variable. The play-next to work you'll need to get the list of active players (like what I am doing) and use the ID of the most active one (the one playing your video) and advance one track.

**Comment by elpraga** [comment]
Thanks for the tip. I will check it out and post the results here..

**Comment by nawar** [comment]
Have you managed to figure this out?

**Comment by elpraga** [comment]
Not yet, but I wrote a very simple python frontend would you be interested to have a look at it and to add it if you like it?

**Comment by nawar** [comment]
Hmm.. let me know where it is and I'll take a look

**Comment by elpraga** [comment]
I still did not figured out how to do it in a clean way, but I did implement seeking in kodi-cli, and subsequently I added playing the next in playlist by seeking to 99.999 percent of the current song.

If you find out a cleaner way how to do it, I will gladly change it.

I also updated the simple frontend to GTK3. You can check the changes here: https://github.com/elpraga/kodi-cli

I use the code to learn, so it is not as clean as yours, so I better left it in my repo.

Cheers!

**Comment by nawar** [comment]
I'll check it out today/this week when I get the time.
